# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiofl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_insercao', models.DateTimeField(auto_now_add=True, verbose_name='Data de insercao')),
                ('foto', models.FileField(blank=True, null=True, upload_to='audio_uploads', verbose_name='Foto')),
            ],
        ),
    ]
